### ISSUE TITLE
Add Support for Auto Updates

### ISSUE THREAD

**Issue by jason-riddle** [jason-riddle/ansible-role-tailscale#109]
Tailscale now supports auto updates.

This feature was made GA on Feb 14 (https://tailscale.com/changelog#2024-02-14). It was first introduced, in beta, on Oct 30, 2023 in v1.52.0 (https://tailscale.com/changelog#2023-10-30)

To enable auto updates, run `tailscale set --auto-update=true`. Here's an example in ansible

```yml
- name: Enable auto updates.
  command: tailscale set --auto-update=true
  changed_when: false
```

To disable auto updates, run `tailscale set --auto-update=false`. Here's an example in ansible

```yml
- name: Disable auto updates.
  command: tailscale set --auto-update=false
  changed_when: false
```

You can also run a one-off command like so

```bash
ansible cluster --module-name ansible.builtin.command --args='tailscale set --auto-update=false' --one-line
```

Perhaps `tailscale status --json` will show the current value?

See https://tailscale.com/kb/1067/update?tab=linux for more info.

What would be nice is if there was a way to configure this in a native ansible manner. So maybe,

```yml
tailscale_auto_update_enabled: false
```

Which means, by default leave it as disabled. To enable, set the variable to `true`.
