### ISSUE TITLE
Investigate how to authorize without exposing key

### ISSUE THREAD

**Issue by jason-riddle** [jason-riddle/ansible-role-tailscale#2]
This is problematic

```yml
- name: Run the authorize command.
  become: true
  command: "tailscale up --authkey {{ tailscale_authorize_key }}"
```

This is because the authorize key will show up in the ansible logs. I'd like to avoid using `no_log: true` because then it's not possible to debug why a command failed.

This looks promising: https://serverfault.com/a/984374. It looks like you can provide the secret via stdin and it would still be hidden from the logs.
